### ISSUE TITLE
Libertine Fonts not found

### ISSUE THREAD

**Issue by markusritschel** [vinay0410/tectonic-action#5]
Hi,
I wanted to give tectonic-action a try. In my document I'm using the Libertine Fonts, which somehow cannot get found by tectonic. Is this a bug or can I add the fonts somehow to my github workflow? The error I get is the following:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Linux Libertine O" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.57 \setsansfont
                 {Linux Biolinum O}
No pages of output.
```
Thanks a lot in advance,
Markus

PS.: When compiling on my local machine, I don't include the fonts via `\usepacke{libertine}` but use fontspec and the font installed on my system.

**Comment by vinay0410** [comment]
Hi @markusritschel , Thanks for taking the time to raise this.
The main USP of tectonic is that it can find and install your dependencies automatically.
By the above error I am not sure if "tectonic found this dependency but failed to download it", or "tectonic failed to detect that the above font is a dependency after all".

>>> PS.: When compiling on my local machine, I don't include the fonts via \usepacke{libertine} but use fontspec and the font installed on my system.

Do you use [tectonic](https://tectonic-typesetting.github.io/en-US/) to compile locally ?

Anyways, it would be much helpful if you could link the repo which you are compiling, so that I can try to debug the same.

**Comment by markusritschel** [comment]
Hi @vinay0410,
Thanks for the quick reply. No, I used xelatex on my local computer so far. It seems that tectonic cannot deal with symbolic font names but needs the exact file names for compiling, see also [issue#372](https://github.com/tectonic-typesetting/tectonic/issues/372). So, it's not an issue caused by your action but by tectonic's side.

**Comment by markusritschel** [comment]
I think, we can close this issue therfore.
